"""booking with projectId

Revision ID: 0203c0fcbc3b
Revises: 7e472917fd8b
Create Date: 2022-09-15 14:00:22.975402

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '0203c0fcbc3b'
down_revision = '7e472917fd8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("FK_bookings_project", 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint("FK_bookings_project", type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###
