"""Added operator relation

Revision ID: 32d068cc965e
Revises: a53f80c32071
Create Date: 2021-04-26 16:02:24.849734

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '32d068cc965e'
down_revision = 'a53f80c32071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operator_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_booking_operator_id',
                                    'users', ['operator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_booking_operator_id',
                                 type_='foreignkey')
        batch_op.drop_column('operator_id')

    # ### end Alembic commands ###
