"""Added Pucks table

Revision ID: 7e472917fd8b
Revises: e42c1d77a566
Create Date: 2021-12-17 08:54:04.732621

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utc


# revision identifiers, used by Alembic.
revision = '7e472917fd8b'
down_revision = 'e42c1d77a566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pucks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('dewar', sa.Integer(), nullable=True),
    sa.Column('cane', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    with op.batch_alter_table('pucks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pucks_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pucks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pucks_code'))

    op.drop_table('pucks')
    # ### end Alembic commands ###
